#specify the directory the output is in
dir.name <- "spatialStructure/datasets/HumanData/analyses/haak_analyses/spatial/k_3"

#then you're off to the races!
setwd(dir.name)

#load in the output file (generated by the MCMC)
#and the data.list, which contains metadata
load(list.files(pattern="output"))
load(list.files(pattern="data.list"))

#check out what's in data.list
str(data.list)

#now read in the functions for visualizing run output
source("spatialStructure/code/viz_funcs.R")

#example fig with sample names
pop.names <- row.names(data.list$sample.covariance)
quartz(width=10,height=5)
make.structure.plot(data.list,super.list,sample.names=pop.names)

#another example fig, sorted by time
pop.order <- order(data.list$time.coords)
quartz(width=10,height=5)
make.structure.plot(data.list,super.list,sample.names=pop.names,sample.order=pop.order)

#another example fig, sorted by time with a different cluster order
pop.order <- order(data.list$time.coords)
quartz(width=10,height=5)
make.structure.plot(data.list,super.list,sample.names=pop.names,sample.order=pop.order,cluster.order=c(2,1,3))

#ok and now you can take a look at nuggets
quartz(width=10,height=5)
plot(super.list$parameter.list$nuggets,type='n')
	text(super.list$parameter.list$nuggets,labels=pop.names,cex=0.5)

#and admixture proportions
quartz(width=10,height=9)
layout(matrix(c(1,2,3),nrow=3,ncol=1))
plot(super.list$parameter.list$admix.proportions[,1],type='n')
	text(super.list$parameter.list$admix.proportions[,1],labels=pop.names,cex=0.5)
plot(super.list$parameter.list$admix.proportions[,2],type='n')
	text(super.list$parameter.list$admix.proportions[,2],labels=pop.names,cex=0.5)
plot(super.list$parameter.list$admix.proportions[,3],type='n')
	text(super.list$parameter.list$admix.proportions[,3],labels=pop.names,cex=0.5)
